apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: soap-app
  namespace: demo
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      path: /metrics
      port: prometheus
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app
          targetLabel: app
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
    - bearerTokenSecret:
        key: ''
      path: /actuator/prometheus
      port: management
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app
          targetLabel: application
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
          replacement: $1
          separator: ;
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app: soap-app
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: soap-app
  namespace: demo
  labels:
    monitoring-key: middleware
    prometheus: application-monitoring
    role: alert-rules
spec:
  groups:
    - name: general.rules
      rules:
        - alert: SoapAppInstanceNotAvailable
          annotations:
            description: >-
              Soap app instance in namespace {{ $labels.namespace }} has not
              been available for the last 5 minutes.
            summary: 'Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN'
          expr: >-
            (1 - absent(kube_pod_status_ready{namespace="demo", condition="true"}
            * on (pod) group_left (label_component)
            kube_pod_labels{label_app="soap-app", namespace="demo"})) == 0
          for: 5m
          labels:
            severity: critical

